Repository ublue-os/aurora, pull requests merged in 2025-07, with the labels that each got.

#667 feat(motd): add KDE donation URL
  system_files/shared/usr/share/ublue-os/motd/tips/10-tips.md
Labels: enhancement, lgtm, size:XS

#671 chore: revert qt6-qtwayland pin
  build_files/base/18-workarounds.sh
Labels: upstream, lgtm, size:XS

#677 feat: add bazaar to beta image
  build_files/base/10-beta.sh
  build_files/shared/build-base.sh
  system_files/shared/usr/share/kde-settings/kde-profile/default/xdg/krunnerrc
  system_files/shared/usr/share/ublue-os/bazaar/blocklist.txt
  system_files/shared/usr/share/ublue-os/bazaar/browse.png
  system_files/shared/usr/share/ublue-os/bazaar/config.yaml
  system_files/shared/usr/share/ublue-os/bazaar/favourites.png
  system_files/shared/usr/share/ublue-os/bazaar/music.png
Labels: enhancement, lgtm, size:L

#682 chore: cleanup beta workflow
  .github/workflows/build-image-beta.yml
Labels: github_actions, lgtm, size:XS

#683 feat(beta): replace discover with bazaar on panel and kickoff
  build_files/base/10-beta.sh
Labels: enhancement, lgtm, size:XS

#688 fix: theme parsing error: gtk.css
  system_files/shared/etc/skel/.config/gtk-3.0/window_decorations.css
Labels: bug, lgtm, size:XS

#691 chore(bazaar): change images to jxl
  system_files/shared/usr/share/ublue-os/bazaar/ai.jxl
  system_files/shared/usr/share/ublue-os/bazaar/ai.png
  system_files/shared/usr/share/ublue-os/bazaar/browse.jxl
  system_files/shared/usr/share/ublue-os/bazaar/browse.png
  system_files/shared/usr/share/ublue-os/bazaar/config.yaml
  system_files/shared/usr/share/ublue-os/bazaar/developers.jxl
  system_files/shared/usr/share/ublue-os/bazaar/developers.png
  system_files/shared/usr/share/ublue-os/bazaar/favourites.jxl
  system_files/shared/usr/share/ublue-os/bazaar/favourites.png
  system_files/shared/usr/share/ublue-os/bazaar/music.jxl
  system_files/shared/usr/share/ublue-os/bazaar/music.png
  system_files/shared/usr/share/ublue-os/bazaar/office.jxl
  system_files/shared/usr/share/ublue-os/bazaar/office.png
  system_files/shared/usr/share/ublue-os/bazaar/utilities.jxl
  system_files/shared/usr/share/ublue-os/bazaar/utilities.png
Labels: lgtm, size:S

#701 chore(kernel): pin stable to 6.14.11
  .github/workflows/build-image-stable.yml
Labels: github_actions, lgtm, size:XS

#690 feat: add toggle-dinosaurs ujust recipe
  just/aurora-system.just
  system_files/shared/usr/lib/systemd/user/bluefin-wallpaper@.service
  system_files/shared/usr/libexec/ublue-bluefin-plasma-wallpaper
Labels: enhancement, lgtm, size:M

#713 fix(beta): pin libdex to 0.9.1
  build_files/base/10-beta.sh
Labels: bug, lgtm, size:XS

#717 fix(build): update beta path to use correct tag
  Justfile
Labels: lgtm, size:XS

#728 feat(beta): add sudo-rs
  build_files/base/10-beta.sh
Labels: enhancement, lgtm, size:XS

#732 feat(ci): consistently use rootful container storage
  .github/workflows/reusable-build.yml
  Justfile
Labels: github_actions, lgtm, size:S

#736 fix(beta): update Bazaar banner alignment
  system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Labels: lgtm, size:S

#735 feat(beta): hide Discover and add ujust to re-enable
  build_files/base/05-override-install.sh
  build_files/base/10-beta.sh
  just/aurora-beta.just
Labels: enhancement, lgtm, size:L

#739 chore: remove image dropdown from feat request template
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: lgtm, size:S

#737 feat(beta): add more KDE apps to Bazaar
  system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Labels: enhancement, lgtm, size:S

#742 feat: add davfs2 to support Taildrive
  packages.json
Labels: enhancement, lgtm, size:XS

#745 fix(ci): load rechunked image into rootfull storage
  .github/workflows/reusable-build.yml
Labels: github_actions, lgtm, size:S

#755 feat(beta): set bazaar default for mimetype flatpakref
  build_files/base/10-beta.sh
Labels: enhancement, lgtm, size:XS
