Repository ublue-os/aurora, pull requests merged in 2025-08, with the labels that each got.

#758 chore: remove unnecessary action
  .github/workflows/reusable-build.yml
Labels: github_actions, lgtm, size:XS

#764 chore: remove changelog.md
  CHANGELOG.md
Labels: documentation, lgtm, size:XS

#762 feat: move to ublue-os devcontainer
  .devcontainer.json
  .devcontainer/devcontainer.json
  .gitignore
Labels: enhancement, lgtm, size:M

#775 feat: update rebase-helper
  system_files/shared/usr/bin/ublue-rollback-helper
Labels: enhancement, lgtm, size:XS

#778 chore: copy toggle iwd ujust recipe from bazzite
  just/aurora-system.just
Labels: lgtm, size:M

#780 feat(beta): add Bazaar banners 5 and 6
  system_files/shared/usr/share/ublue-os/bazaar/05-aurora-bazaar.jxl
  system_files/shared/usr/share/ublue-os/bazaar/06-aurora-bazaar.jxl
  system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Labels: enhancement, lgtm, size:XS

#782 chore: update readme badge
  README.md
Labels: documentation, size:XS

#789 feat(bazaar): add Qt-based yt-dlp GUI
  system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Labels: enhancement, lgtm, size:XS

#794 fix(beta): move Bazaar text alignment to the correct side
  system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Labels: bug, lgtm, size:S

#799 feat(bazaar): add Kdenlive + remove org.gnome.Fractal
  system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Labels: enhancement, lgtm, size:XS

#776 feat: move to centralized flatpaks lists
  .github/workflows/build-image-latest-hwe.yml
  .github/workflows/build-image-latest-main.yml
  .github/workflows/build-image-stable.yml
  .github/workflows/reusable-build-iso-anaconda-webui.yml
  .github/workflows/reusable-build-iso-anaconda.yml
  .github/workflows/reusable-build-iso-readymade.yml
  Containerfile
  Justfile
  aurora_flatpaks/flatpaks
  build_files/shared/build-base.sh
  dx_flatpaks/flatpaks
  flatpaks/system-flatpaks-dx.list
  flatpaks/system-flatpaks.list
Labels: github_actions, lgtm, size:M

#810 fix: typo in iwd toggle script
  just/aurora-system.just
Labels: bug, lgtm, size:XS

#785 feat: enable bazaar in main images
  .github/workflows/build-images.yml
  build_files/base/10-beta.sh
  build_files/base/11-bazaar.sh
  build_files/shared/build-base.sh
  just/aurora-apps.just
  just/aurora-beta.just
  packages.json
  system_files/shared/usr/share/kde-settings/kde-profile/default/xdg/krunnerrc
Labels: enhancement, lgtm, size:L

#818 fix: update logic for applying framework laptop 13 fixes
  system_files/shared/usr/share/ublue-os/system-setup.hooks.d/10-framework.sh
Labels: bug, lgtm, size:M

#825 feat: enable progress for ISO cloudflare upload
  .github/workflows/reusable-build-iso-anaconda.yml
Labels: github_actions, lgtm, size:XS

#827 fix(framework): use KDE javascript to set icon
  system_files/shared/usr/share/ublue-os/user-setup.hooks.d/60-framework-kde-launcher.sh
Labels: bug, framework, lgtm, size:M

#839 chore: remove ramalama from image
  just/aurora-apps.just
  packages.json
Labels: dependencies, lgtm, size:S

#850 fix(nvidia): Force NGL for GTK apps for now
  build_files/base/18-workarounds.sh
Labels: bug, lgtm, size:XS

#851 chore: remove bazaar libdex workaround
  build_files/base/11-bazaar.sh
Labels: lgtm, size:XS

#852 chore: remove unnecessary plymouth kcm disablement
  system_files/shared/usr/share/kde-settings/kde-profile/default/xdg/kdeglobals
Labels: lgtm, size:XS

#856 feat(bazaar): add OnlyOffice
  system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Labels: enhancement, lgtm, size:XS

#831 feat: add sddm setting
  system_files/shared/usr/lib/sddm/sddm.conf.d/kde_settings.conf
Labels: enhancement, lgtm, size:XS

#858 feat(bazaar): remove Damask, add Cameractrls
  system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Labels: enhancement, lgtm, size:XS

#859 chore: remove the bazaar specific nvidia fix
  build_files/base/11-bazaar.sh
Labels: lgtm, size:XS

#864 style: remove manual linebreak
  .github/changelogs.py
Labels: lgtm, size:XS

#877 feat(bazaar): add few devtools
  system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Labels: enhancement, lgtm, size:XS

#880 fix(bazaar): add fwupd to blocklist
  system_files/shared/usr/share/ublue-os/bazaar/blocklist.txt
Labels: lgtm, size:XS

#892 chore(bazaar): block kde apps that are native
  system_files/shared/usr/share/ublue-os/bazaar/blocklist.txt
Labels: lgtm, size:XS

#894 fix: Revert "feat(motd): add mention of bbrew to motd"
  system_files/shared/usr/share/ublue-os/motd/template.md
Labels: lgtm, size:XS

#893 fix: disable discover notifier
  build_files/base/11-bazaar.sh
  just/aurora-apps.just
Labels: bug, lgtm, size:S
