Repository ublue-os/aurora, pull requests merged in 2025-04, with the labels that each got.

#307 chore: remove plasma welcome fedora branding
  packages.json
Labels: lgtm, size:M

#306 chore: remove beta workarounds
  build_files/base/03-install-kernel-akmods.sh
  build_files/dx/02-install-kernel-akmods-dx.sh
Labels: lgtm, size:M

#309 chore: remove hidden system-flatpak-install from the ujust list
  just/aurora-system.just
Labels: lgtm, size:XS

#312 chore: enable openrazer kernel module for Fedora 42
  build_files/base/03-install-kernel-akmods.sh
Labels: lgtm, size:XS

#314 chore: move to packages repo
  build_files/base/05-override-install.sh
  packages.json
  system_files/kinoite/usr/share/ublue-os/aurora-logo.txt
  system_files/shared/usr/share/pixmaps/ublue-discourse.svg
  system_files/shared/usr/share/pixmaps/ublue-docs.svg
  system_files/shared/usr/share/pixmaps/ublue-update.svg
  system_files/shared/usr/share/ublue-os/fastfetch.jsonc
Labels: dependencies, lgtm, size:L

#315 chore: simplify packages.sh install scripts
  build_files/base/04-packages.sh
  build_files/dx/03-packages-dx.sh
  packages.json
Labels: lgtm, size:L

#320 feat: add devcontainer
  .devcontainer/devcontainer.json
Labels: enhancement, lgtm, size:M

#324 fix: temp fix for rpmfusion on f42
  build_files/base/03-install-kernel-akmods.sh
Labels: upstream, lgtm, size:S

#322 feat: Add samsung unified linux driver (#2321)
  packages.json
Labels: dependencies, lgtm, size:XS

#326 chore: beta should build even if rpmfusion isn't working
  build_files/base/03-install-kernel-akmods.sh
Labels: lgtm, size:M

#327 chore: switch from ublue-update to uupd as default automatic updater
  build_files/base/05-override-install.sh
  build_files/base/17-cleanup.sh
  packages.json
  system_files/shared/etc/ublue-update/ublue-update.toml
  system_files/shared/usr/share/ublue-os/just/10-update.just
  system_files/shared/usr/share/ublue-os/topgrade-bootc.toml
  system_files/shared/usr/share/ublue-os/topgrade.toml
Labels: lgtm, size:M

#329 fix: Revert "chore: move to packages repo (#314)"
  build_files/base/05-override-install.sh
  packages.json
  system_files/kinoite/usr/share/ublue-os/aurora-logo.txt
  system_files/shared/usr/share/pixmaps/ublue-discourse.svg
  system_files/shared/usr/share/pixmaps/ublue-docs.svg
  system_files/shared/usr/share/pixmaps/ublue-update.svg
  system_files/shared/usr/share/ublue-os/fastfetch.jsonc
Labels: lgtm, size:L

#331 chore: bring back packages from copr
  build_files/base/05-override-install.sh
  packages.json
  system_files/kinoite/usr/share/ublue-os/aurora-logo.txt
  system_files/shared/usr/share/pixmaps/ublue-discourse.svg
  system_files/shared/usr/share/pixmaps/ublue-docs.svg
  system_files/shared/usr/share/pixmaps/ublue-update.svg
  system_files/shared/usr/share/ublue-os/fastfetch.jsonc
Labels: lgtm, size:L

#328 feat: remove rpmfusion and replace v4l2loopback from terra
  build_files/base/03-install-kernel-akmods.sh
Labels: dependencies, lgtm, size:S

#319 chore: move more stuff to packages repo
  packages.json
  system_files/shared/etc/geoclue/conf.d/99-beacondb.conf
  system_files/shared/usr/share/ublue-os/homebrew/aurora-cli.Brewfile
  system_files/shared/usr/share/ublue-os/homebrew/kubernetes.Brewfile
Labels: lgtm, size:S

#334 chore: add gates for f42 launch
  build_files/base/05-override-install.sh
  packages.json
Labels: lgtm, size:M

#332 chore: add skanpage flatpak to list
  aurora_flatpaks/flatpaks
Labels: size:XS

#336 chore: remove topgrade
  packages.json
Labels: lgtm, size:XS

#342 fix: add default terminal font back to image
  packages.json
Labels: size:XS

#286 chore: remove DevPod rpm
  packages.json
Labels: enhancement, lgtm, size:XS

#343 chore: enable swapping of kio and switcheroo on F42
  build_files/base/05-override-install.sh
Labels: lgtm, size:S

#346 fix(dx): install docker-ce from test repo on F42
  build_files/dx/04-override-install-dx.sh
  packages.json
  system_files/dx/etc/yum.repos.d/docker-ce.repo
Labels: lgtm, size:S

#347 chore: remove f40 from package list
  packages.json
Labels: lgtm, size:S

#345 feat(dx): add devtoolbox and DevPod flatpaks to -dx
  dx_flatpaks/flatpaks
Labels: enhancement, lgtm, size:XS

#350 fix: rename kf6-kio package on terra
  build_files/base/05-override-install.sh
Labels: lgtm, size:XS

#351 feat: bring back fw-fanctrl for f42
  packages.json
Labels: enhancement, lgtm, size:XS

#349 chore: remove akmod workaround for beta
  build_files/base/03-install-kernel-akmods.sh
Labels: lgtm, size:S

#355 feat: enable sunshine + add ujust script
  build_files/base/02-install-copr-repos.sh
  build_files/base/17-cleanup.sh
  just/aurora-apps.just
  packages.json
Labels: enhancement, lgtm, size:M

#356 fix: Revert "feat: remove v4l2loopback and rpmfusion for Fedora 42+"
  build_files/base/03-install-kernel-akmods.sh
Labels: lgtm, size:S

#357 fix: setup-cockpit recipe
  just/aurora-apps.just
Labels: lgtm, size:M

#358 chore: use docker packages from the stable repo
  build_files/dx/04-override-install-dx.sh
  packages.json
  system_files/dx/etc/yum.repos.d/docker-ce.repo
Labels: lgtm, size:S

#360 feat: add incredibly important essential package (glorpfetch)
  packages.json
Labels: enhancement, lgtm, size:XS

#364 fix: remove xpadneo
  build_files/base/03-install-kernel-akmods.sh
Labels: lgtm, size:XS

#368 fix(hwe): switch to skip-unavailable
  build_files/base/09-hwe-additions.sh
Labels: lgtm, size:XS

#362 chore: Revert "disable building HWE for now"
  .github/workflows/build-images.yml
Labels: github_actions, lgtm, size:XS

#369 chore: remove skanpage rpm
  packages.json
Labels: lgtm, size:XS

#370 fix(nvidia-open): correctly identify nvidia-open on image-info.json
  build_files/base/00-image-info.sh
Labels: lgtm, size:XS

#371 chore: align buildflow
  .github/dependabot.yml
  .github/workflows/reusable-build.yml
Labels: github_actions, lgtm, size:M

#377 fix: remove incus alias
  just/aurora-apps.just
Labels: lgtm, size:XS

#375 fix: devpod flatpak fix for nvidia
  system_files/shared/usr/libexec/ublue-user-setup
Labels: bug, lgtm, size:XS

#374 fix(flatpak): remove fedora flatpak service and repos
  Justfile
  build_files/base/17-cleanup.sh
Labels: lgtm, size:XS

#376 fix: show prompt for installing stress-ng via brew if not installed
  just/aurora-system.just
Labels: bug, lgtm, size:S

#381 fix: make samba usershares work OOTB
  build_files/base/07-base-image-changes.sh
Labels: lgtm, size:XS

#383 fix(rebase-helper): Guard rebase helper
  system_files/shared/usr/bin/ublue-rollback-helper
Labels: lgtm, size:XS

#359 chore: move dx workarounds to packages repo
  packages.json
  system_files/dx/usr/lib/systemd/system/libvirt-workaround.service
  system_files/dx/usr/lib/tmpfiles.d/libvirt-workaround.conf
Labels: lgtm, size:S

#386 chore: use aurora-plymouth package
  build_files/base/05-override-install.sh
  build_files/base/07-base-image-changes.sh
  system_files/shared/usr/share/plymouth/themes/spinner/kinoite-watermark.png
Labels: lgtm, size:XS

#387 chore: cleanup everything brew-related that ublue-brew entirely covers
  build_files/base/10-brew.sh
  build_files/shared/build-base.sh
  system_files/shared/usr/lib/systemd/system-preset/02-homebrew-update.preset
  system_files/shared/usr/lib/systemd/system/brew-update.service
  system_files/shared/usr/lib/systemd/system/brew-update.timer
  system_files/shared/usr/lib/systemd/system/brew-upgrade.service
  system_files/shared/usr/lib/systemd/system/brew-upgrade.timer
Labels: lgtm, size:M

#384 chore(iso): drop legacy nvidia ISOs
  .github/workflows/build-iso-latest.yml
  .github/workflows/reusable-build-iso.yml
Labels: github_actions, lgtm, size:XS

#389 chore: use main repo for nvidia-install.sh
  build_files/base/03-install-kernel-akmods.sh
Labels: lgtm, size:XS

#390 feat(just): add ujust for installing fonts from brew
  just/aurora-system.just
Labels: enhancement, lgtm, size:S

#392 chore: get rid of glorpfetch
  packages.json
Labels: dependencies, lgtm, size:XS

#397 fix: flathub should be added as system if not exists
  just/aurora-system.just
Labels: size:XS

#398 chore: remove kcharselect
  aurora_flatpaks/flatpaks
  packages.json
Labels: lgtm, size:XS

#396 feat: add docs pdf
  build_files/base/05-override-install.sh
Labels: documentation, lgtm, size:XS

#395 chore: add upstream bootc config for nvidia and bootc install
  build_files/base/03-install-kernel-akmods.sh
  system_files/shared/usr/lib/bootc/install/20-aurora.toml
Labels: lgtm, size:XS

#400 chore: Update bug-report
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: size:XS

#399 fix: add temporary workaround service for missing `/etc/hostname` file
  build_files/base/17-cleanup.sh
  system_files/shared/usr/lib/systemd/system/ublue-fix-hostname.service
Labels: bug, lgtm, size:S

#401 fix: /etc/hostname fixup
  system_files/shared/usr/lib/systemd/system/ublue-fix-hostname.service
Labels: bug, size:XS

#402 chore(readme): Replace CONTRIBUTING link from Bluefin to Universal Blue
  README.md
Labels: documentation, lgtm, size:XS

#405 chore: hide beta builds after f42 release
  README.md
Labels: documentation, lgtm, size:XS

#403 chore: pin Stable to kernel 6.13.8
  .github/workflows/build-image-stable.yml
Labels: github_actions, lgtm, size:XS

#406 feat(ci): switch to renovate from cronjobs
  .github/renovate.json5
  .github/workflows/build-image-latest-hwe.yml
  .github/workflows/build-image-latest-main.yml
  .github/workflows/build-image-stable.yml
  image-versions.yml
Labels: github_actions, lgtm, size:S

#408 fix: fix small typo in just recipes
  just/aurora-apps.just
Labels: lgtm, size:XS
