Repository ublue-os/aurora, pull requests merged in 2025-05, with the labels that each got.

#412 fix(just): add current user to dx-groups instead of root
  just/aurora-system.just
Labels: lgtm, size:XS

#416 feat: enable uupd for all images
  build_files/base/17-cleanup.sh
  packages.json
Labels: enhancement, lgtm, size:XS

#419 chore: remove fedora-chromium-config* and fedora-bookmarks package
  packages.json
Labels: dependencies, lgtm, size:XS

#422 feat: use ublue-setup-services for setup services
  build_files/base/17-cleanup.sh
  build_files/dx/09-cleanup-dx.sh
  packages.json
  system_files/dx/usr/share/ublue-os/user-setup.hooks.d/10-vscode.sh
  system_files/shared/etc/profile.d/sb-key-notify-autostart.sh
  system_files/shared/etc/skel/.config/autostart/sb-key-notify.desktop
  system_files/shared/etc/ublue-os/setup.json
  system_files/shared/usr/bin/sb-key-notify
  system_files/shared/usr/lib/systemd/system/check-sb-key.service
  system_files/shared/usr/lib/systemd/system/ublue-system-setup.service
  system_files/shared/usr/lib/systemd/user/ublue-flatpak-manager.service
  system_files/shared/usr/lib/systemd/user/ublue-user-setup.service
  system_files/shared/usr/libexec/check-sb-key.sh
  system_files/shared/usr/libexec/ublue-privileged-user-setup
  system_files/shared/usr/libexec/ublue-system-setup
  system_files/shared/usr/share/ublue-os/privileged-setup.hooks.d/10-tailscale.sh
  system_files/shared/usr/share/ublue-os/privileged-setup.hooks.d/99-flatpaks.sh
  system_files/shared/usr/share/ublue-os/system-setup.hooks.d/10-framework.sh
  system_files/shared/usr/share/ublue-os/user-setup.hooks.d/99-privileged.sh
Labels: enhancement, lgtm, size:L

#423 chore: cleanup f40 mentions from build scripts
  Containerfile
  build_files/base/16-bootc.sh
  build_files/shared/build-base.sh
Labels: lgtm, size:S

#427 fix(uupd): enable the service without conditions
  build_files/base/17-cleanup.sh
Labels: lgtm, size:XS

#425 fix: remove kns + fwupd backends from Discover more reliably
  build_files/base/07-base-image-changes.sh
Labels: lgtm, size:XS

#431 chore: pin iso's to use F41 for installer
  Justfile
Labels: upstream, lgtm, size:XS

#432 chore: remove LXD from group scripts and references
  build_files/dx/01-install-copr-repos-dx.sh
  system_files/dx/usr/lib/systemd/system/aurora-dx-groups.service
  system_files/dx/usr/libexec/aurora-dx-groups
Labels: lgtm, size:XS

#434 fix: restore fwupd backend to discover
  build_files/base/07-base-image-changes.sh
Labels: lgtm, size:XS

#435 chore: stop building -dx, HWE and latest ISOs
  .github/workflows/build-iso-latest.yml
  .github/workflows/build-isos.yml
  .github/workflows/reusable-build-iso.yml
Labels: github_actions, lgtm, size:XS

#436 chore: cleanup old distrobox and unneccessary charm repo
  build_files/base/17-cleanup.sh
  system_files/dx/usr/bin/aurorabox-enter
  system_files/shared/etc/distrobox/distrobox.conf
  system_files/shared/etc/distrobox/distrobox.example
  system_files/shared/etc/yum.repos.d/charm.repo
Labels: lgtm, size:M

#437 chore: bump rechunker and ISO generator
  Justfile
Labels: dependencies, lgtm, size:XS

#441 chore: update readme to fix star history chart
  README.md
Labels: documentation, lgtm, size:XS

#445 fix(iso): Get Anaconda ISOs updated
  .github/renovate.json5
  .github/workflows/build-image-latest-hwe.yml
  .github/workflows/build-image-stable.yml
  .github/workflows/build-iso-stable.yml
  .github/workflows/build-isos.yml
  .github/workflows/reusable-build-iso.yml
  Justfile
Labels: github_actions, lgtm, size:M

#448 fix(iso-build): change the build space part
  .github/workflows/reusable-build-iso.yml
Labels: github_actions, lgtm, size:XS

#450 fix(changelogs): fix changelogs automation
  .github/workflows/generate-release.yml
Labels: github_actions, lgtm, size:XS

#454 feat: enable input-remapper service by default
  build_files/base/17-cleanup.sh
Labels: enhancement, lgtm, size:XS

#464 chore: remove guards from rollback-helper
  system_files/shared/usr/bin/ublue-rollback-helper
Labels: lgtm, size:XS

#456 feat: add aurora branding to anaconda installer
  .github/workflows/reusable-build-iso.yml
  Justfile
  iso_files/.gitkeep
Labels: enhancement, github_actions, lgtm, size:S

#466 fix: create devmode version directory
  system_files/dx/usr/libexec/aurora-dx-groups
Labels: lgtm, size:S

#467 fix: ublue-fix-hostname unit errors
  system_files/shared/usr/lib/systemd/system/ublue-fix-hostname.service
Labels: bug, lgtm, size:XS

#468 fix(iso): remove double build args
  .github/workflows/reusable-build-iso.yml
Labels: github_actions, lgtm, size:XS

#472 feat: add polkit rules pkg
  packages.json
Labels: enhancement, lgtm, size:XS

#476 fix(iso): Use F41 for ISO
  Justfile
Labels: bug, lgtm, size:XS

#478 fix(iso): remove arch from flatpaks
  aurora_flatpaks/flatpaks
  dx_flatpaks/flatpaks
  iso_files/.gitkeep
Labels: lgtm, size:M

#479 feat: replace gtk3 firewall with plasma-firewall
  packages.json
Labels: enhancement, lgtm, size:XS

#483 chore: delete old logos from repo
  system_files/shared/usr/share/pixmaps/fedora-logo-small.png
  system_files/shared/usr/share/pixmaps/fedora-logo-sprite.png
  system_files/shared/usr/share/pixmaps/fedora-logo-sprite.svg
  system_files/shared/usr/share/pixmaps/fedora-logo.png
  system_files/shared/usr/share/pixmaps/fedora-logo.svg
  system_files/shared/usr/share/pixmaps/fedora_logo_med.png
  system_files/shared/usr/share/pixmaps/fedora_whitelogo.svg
  system_files/shared/usr/share/pixmaps/system-logo-white.png
  system_files/shared/usr/share/pixmaps/system-logo.png
Labels: lgtm, size:XS

#482 feat: Create livecd with anaconda webui
  .github/workflows/build-image-latest-hwe.yml
  .github/workflows/build-image-latest-main.yml
  .github/workflows/build-image-stable.yml
  .github/workflows/generate-release.yml
  .github/workflows/reusable-build-iso-anaconda.yml
  .github/workflows/reusable-build-iso.yml
  .github/workflows/reusable-build.yml
  Justfile
  iso_files/aurora.repo
  iso_files/configure_iso_anaconda.sh
  iso_files/system-flatpaks-dx.list
  iso_files/system-flatpaks.list
Labels: enhancement, github_actions, lgtm, size:L

#486 fix(iso): fix live cd workflow
  .github/workflows/reusable-build-iso-anaconda.yml
Labels: github_actions, lgtm, size:S

#487 fix(iso): update workflow
  .github/workflows/reusable-build-iso-anaconda.yml
Labels: size:XS

#493 fix(readymade): fix workflow iso upload
  .github/workflows/reusable-build-iso-readymade.yml
Labels: size:XS

#494 fix(readymade): flatpaks for the iso
  .github/workflows/reusable-build-iso-readymade.yml
  iso_files/configure_iso.sh
Labels: size:XS

#497 Revert "chore(readymade): taidan enablement"
  iso_files/configure_iso.sh
Labels: size:XS

#498 chore(iso): remove network and root pw sections from anaconda
  iso_files/configure_iso_anaconda.sh
Labels: size:XS

#502 fix(just): use rpm -qa for list-installed-rpms
  just/aurora-apps.just
Labels: lgtm, size:XS

#505 chore: remove override for cursor in gtk apps
  system_files/shared/usr/libexec/ublue-user-setup
Labels: upstream, lgtm, size:XS

#513 fix(pin): atheros-firmware downgrade to 20250311-1
  build_files/base/18-workarounds.sh
Labels: bug, lgtm, size:S

#515 feat: change default wallpaper from chandeleer
  build_files/base/07-base-image-changes.sh
  system_files/shared/usr/share/plasma/look-and-feel/dev.getaurora.aurora.desktop/contents/plasmoidsetupscripts/org.kde.plasma.folder.js
Labels: enhancement, lgtm, size:XS

#518 chore(ci): Build live anaconda ISO weekly
  .github/workflows/reusable-build-iso-anaconda.yml
Labels: github_actions, lgtm, size:XS

#522 fix: aurora-groups service
  system_files/dx/usr/libexec/aurora-dx-groups
  system_files/shared/usr/libexec/aurora-groups.sh
Labels: lgtm, size:S

#523 fix: update docker extension to container extension
  system_files/dx/usr/libexec/aurora-dx-user-vscode
Labels: upstream, lgtm, size:XS

#525 feat: add exit and open web portal opts to sunshine setup script
  just/aurora-apps.just
Labels: enhancement, lgtm, size:S

#527 chore: remove remaining logos
  system_files/shared/usr/share/icons/hicolor/scalable/distributor-logo-white.svg
  system_files/shared/usr/share/icons/hicolor/scalable/distributor-logo.svg
  system_files/shared/usr/share/icons/hicolor/scalable/places/distributor-logo-white.svg
  system_files/shared/usr/share/icons/hicolor/scalable/places/distributor-logo.svg
Labels: lgtm, size:XS

#532 feat(iso): Move to LiveCD with old anaconda installer
  .github/workflows/reusable-build-iso-anaconda.yml
  iso_files/configure_iso_anaconda.sh
Labels: enhancement, github_actions, size:XS

#534 fix: set SDDM wallpaper to the regular default wallpaper
  build_files/base/07-base-image-changes.sh
Labels: lgtm, size:XS

#535 feat(iso): Move to LiveCD with Anaconda webUI (BETA)
  .github/workflows/reusable-build-iso-anaconda-webui.yml
  iso_files/configure_iso_anaconda-webui.sh
Labels: enhancement, github_actions, size:L

#539 fix(ujust): unindent recipe name after refactor
  just/aurora-system.just
Labels: bug, lgtm, size:XS
