Repository ublue-os/aurora, pull requests merged in 2025-03, with the labels that each got.

#250 feat: expand recipe to rollback broken NVIDIA images
  Justfile
Labels: enhancement, lgtm, size:S

#249 chore: unpin kernel on latest and hwe streams
  .github/workflows/build-image-latest-hwe.yml
  .github/workflows/build-image-latest-main.yml
Labels: github_actions, size:XS

#252 fix: codacy badges on readme
  README.md
Labels: size:XS

#253 fix: codeowners
  .github/CODEOWNERS
Labels: size:XS

#254 chore: remove rpm-ostree cli unwrapping
  build_files/shared/build-base.sh
Labels: lgtm, size:S

#258 fix: update motd tips script
  system_files/shared/usr/share/ublue-os/motd/tips/10-tips.md
Labels: lgtm, size:XS

#256 chore: remove deprecated SBOM workflow
  .github/syft.yml
  .github/workflows/reusable-build.yml
  .github/workflows/reusable-image-scan.yml
Labels: github_actions, lgtm, size:L

#269 fix(devpod): switch back to the ublue copr for devpod
  build_files/base/17-cleanup.sh
  build_files/dx/01-install-copr-repos-dx.sh
Labels: bug, lgtm, size:XS

#270 feat: add container detection to dnf
  system_files/kinoite/usr/bin/dnf
  system_files/kinoite/usr/bin/yum
Labels: enhancement, lgtm, size:XS

#272 fix: add executable perms back for yum
  system_files/kinoite/usr/bin/yum
Labels: bug, lgtm, size:XS

#273 chore: unswap devpod
  build_files/dx/01-install-copr-repos-dx.sh
Labels: size:XS

#274 fix: downgrade dnf5 to 5.2.10 to workaround pulling signing keys
  build_files/shared/build-base.sh
Labels: upstream, lgtm, size:XS

#277 feat: tell discover to only show flatpaks
  build_files/base/07-base-image-changes.sh
Labels: enhancement, lgtm, size:XS

#281 fix: rename kf6-kio package
  build_files/base/05-override-install.sh
Labels: bug, lgtm, size:S

#282 fix: update CODEOWNERS
  .github/CODEOWNERS
Labels: lgtm, size:XS

#287 fix(revert): downgrade dnf5 to 5.2.10
  build_files/shared/build-base.sh
Labels: lgtm, size:XS

#291 chore: remove wl akmod
  build_files/base/03-install-kernel-akmods.sh
Labels: lgtm, size:XS

#290 chore: remove fw-fanctrl
  build_files/base/02-install-copr-repos.sh
  build_files/base/05-override-install.sh
  build_files/base/17-cleanup.sh
  packages.json
Labels: lgtm, size:XS

#294 chore: update rechunker version
  Justfile
Labels: dependencies, lgtm, size:XS

#295 fix: Remove nonAscii file name for iso building
  Justfile
  build_files/base/18-workarounds.sh
Labels: lgtm, size:S

#296 fix: prepend the discover arguments
  build_files/base/07-base-image-changes.sh
Labels: lgtm, size:XS

#298 fix: beta build recipe
  Justfile
  build_files/base/03-install-kernel-akmods.sh
  build_files/base/04-packages.sh
  build_files/base/05-override-install.sh
  build_files/base/17-cleanup.sh
  build_files/dx/02-install-kernel-akmods-dx.sh
  build_files/dx/03-packages-dx.sh
  build_files/dx/09-cleanup-dx.sh
Labels: lgtm, size:L

#299 chore: add beta image badge to README
  README.md
Labels: documentation, size:XS

#303 fix: fix forged on date in fastfetch config
  system_files/shared/usr/share/ublue-os/fastfetch.jsonc
Labels: bug, lgtm, size:XS
