Repository ublue-os/aurora, pull requests merged in 2025-01, with the labels that each got.

#59 fix: revert "fix: remove wl akmod"
  build_files/base/03-install-kernel-akmods.sh
Labels: lgtm

#69 feat: add nvidia-open images
  .github/workflows/build-image-latest.yml
  .github/workflows/build-iso-latest.yml
  .github/workflows/reusable-build-iso.yml
  .github/workflows/reusable-build.yml
  Justfile
  build_files/base/03-install-kernel-akmods.sh
Labels: enhancement, github_actions, lgtm, size:M

#66 chore: remove unused xdg-terminal-exec program
  system_files/kinoite/usr/bin/xdg-terminal-exec
Labels: size:XS

#71 chore(build-dx): consolidate os-release names
  build_files/shared/build-dx.sh
  system_files/kinoite/usr/share/kde-settings/kde-profile/default/xdg/kcm-about-distrorc
Labels: lgtm, size:XS

#72 chore: update some lingering bluefin references
  Justfile
Labels: lgtm, size:XS

#73 chore: remove unused boot_menu.yml file
  boot_menu.yml
Labels: lgtm, size:S

#74 fix: add shebang to /usr/bin/sb-key-notify
  system_files/shared/usr/bin/sb-key-notify
Labels: bug, lgtm, size:XS

#77 chore: remove systemd unit disable for unknown services on aurora-dx
  build_files/dx/09-cleanup-dx.sh
Labels: lgtm, size:XS

#85 fix: artifacthub id
  artifacthub-repo.yml
Labels: lgtm, size:XS

#78 chore: remove VERSION_CODENAME from os-release
  build_files/base/00-image-info.sh
Labels: lgtm, size:XS

#81 fix(actions): try to recover if just fails to install
  .github/workflows/generate-release.yml
  .github/workflows/reusable-build-iso.yml
  .github/workflows/reusable-build.yml
  .github/workflows/shared/install-just.sh
Labels: github_actions, lgtm, size:M

#89 chore: fix link to badge for the stable build
  README.md
Labels: documentation, lgtm, size:XS

#91 fix: move powertop to all images
  packages.json
Labels: lgtm, size:XS

#90 chore(readme): remove badge for the beta builds
  README.md
Labels: documentation, lgtm, size:XS

#95 feat: add ujust recipe to install gaming flatpaks
  just/aurora-apps.just
Labels: enhancement, lgtm, size:S

#44 feat: openrazer-daemon
  build_files/base/02-install-copr-repos.sh
  build_files/base/17-cleanup.sh
  packages.json
  system_files/shared/usr/lib/systemd/system/aurora-groups.service
  system_files/shared/usr/libexec/aurora-groups.sh
Labels: lgtm

#98 fix(hwe): match Bluefin's HWE for Surface devices
  build_files/base/09-hwe-additions.sh
Labels: lgtm, size:M

#105 chore: move aurora-cli to shared ublue-bling script
  build_files/base/18-workarounds.sh
  just/aurora-system.just
  packages.json
  system_files/shared/etc/ublue-os/bling.json
  system_files/shared/usr/libexec/ublue-bling.sh
  system_files/shared/usr/share/ublue-os/aurora-cli/bling.fish
  system_files/shared/usr/share/ublue-os/aurora-cli/bling.sh
Labels: lgtm, size:L

#107 fix(just): fix configure-vfio recipe
  just/aurora-system.just
Labels: lgtm, size:M

#106 fix: Framework 13 AMD support
  system_files/shared/usr/libexec/ublue-system-setup
Labels: bug, framework, lgtm, size:XS

#111 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: lgtm, size:XS

#102 fix: make aurora-groups.sh executable
  system_files/shared/usr/lib/systemd/system/aurora-groups.service
  system_files/shared/usr/libexec/aurora-groups.sh
Labels: bug, lgtm, size:S

#109 chore: move fastfetch configuration to ublue-fastfetch
  packages.json
  system_files/kinoite/etc/profile.d/aurora-fastfetch.sh
  system_files/kinoite/usr/share/fish/vendor_conf.d/aurora-fastfetch.fish
  system_files/shared/usr/libexec/ublue-bling-fastfetch
  system_files/shared/usr/share/ublue-os/fastfetch.jsonc
Labels: lgtm, size:M

#115 chore: Update CODEOWNERS
  .github/CODEOWNERS
Labels: lgtm, size:XS

#110 chore: move MOTD configuration to ublue-motd
  packages.json
  system_files/shared/usr/libexec/ublue-motd
  system_files/shared/usr/share/fish/vendor_functions.d/fish_greeting.fish
  system_files/shared/usr/share/ublue-os/motd/template.md
  system_files/shared/usr/share/ublue-os/motd/themes/blue.json
  system_files/shared/usr/share/ublue-os/motd/themes/green.json
  system_files/shared/usr/share/ublue-os/motd/themes/orange.json
  system_files/shared/usr/share/ublue-os/motd/themes/pink.json
  system_files/shared/usr/share/ublue-os/motd/themes/purple.json
  system_files/shared/usr/share/ublue-os/motd/themes/red.json
  system_files/shared/usr/share/ublue-os/motd/themes/slate.json
  system_files/shared/usr/share/ublue-os/motd/themes/teal.json
  system_files/shared/usr/share/ublue-os/motd/themes/yellow.json
Labels: lgtm, size:XL

#83 fix: pin kernel to 6.11.11 for stable images
  .github/workflows/build-image-stable.yml
Labels: github_actions, lgtm, size:XS

#113 chore: move brew configuration to ublue-brew
  packages.json
  system_files/shared/etc/profile.d/brew-bash-completion.sh
  system_files/shared/etc/security/limits.d/30-brew-limits.conf
  system_files/shared/usr/lib/systemd/system-preset/02-homebrew-update.preset
  system_files/shared/usr/lib/systemd/system/brew-setup.service
  system_files/shared/usr/lib/tmpfiles.d/homebrew.conf
  system_files/shared/usr/share/fish/vendor_conf.d/brew.fish
Labels: lgtm, size:M

#117 feat: add just for installing openrazer gui apps and opentabletdriver service distrobox
  just/aurora-apps.just
Labels: enhancement, lgtm, size:M

#121 fix: rollback stable images to 6.11.8 kernel
  .github/workflows/build-image-stable.yml
Labels: github_actions, lgtm, size:XS

#119 feat: change opendrivertablet to flatpak version from flathub
  just/aurora-apps.just
Labels: enhancement, lgtm, size:M

#123 chore: remove lxd from dx-groups ujust
  just/aurora-system.just
Labels: lgtm, size:XS

#125 fix: Update ublue-system-setup
  system_files/shared/usr/lib/systemd/system/ublue-system-setup.service
  system_files/shared/usr/libexec/ublue-system-setup
Labels: lgtm, size:XS

#127 feat: embed actual image version into os-release
  Containerfile
  Justfile
  build_files/base/00-image-info.sh
Labels: enhancement, lgtm, size:S

#128 fix: fix ujust benchmark
  just/aurora-system.just
Labels: bug, lgtm, size:XS

#136 feat: overrides for Qt/GTK theming in flatpaks
  system_files/shared/usr/libexec/ublue-user-setup
Labels: enhancement, lgtm, size:XS

#135 feat: add org.gtk.Gtk3theme.Breeze for better GTK app integration
  aurora_flatpaks/flatpaks
Labels: enhancement, lgtm, size:XS

#140 fix: fix hwe builds
  build_files/base/09-hwe-additions.sh
Labels: lgtm, size:XS

#139 feat: add workaround for sddm theme (again)
  build_files/base/17-cleanup.sh
  just/aurora-apps.just
  system_files/shared/usr/lib/systemd/system/usr-share-sddm-themes.mount
  system_files/shared/usr/lib/tmpfiles.d/usr-share-sddm-themes.conf 
Labels: enhancement, lgtm, size:M

#141 feat(ci): Enable Docker Building, GHA Log Grouping
  Justfile
  build_files/base/00-image-info.sh
  build_files/base/01-build-fix.sh
  build_files/base/02-install-copr-repos.sh
  build_files/base/03-install-kernel-akmods.sh
  build_files/base/04-packages.sh
  build_files/base/05-override-install.sh
  build_files/base/07-base-image-changes.sh
  build_files/base/08-firmware.sh
  build_files/base/09-hwe-additions.sh
  build_files/base/10-brew.sh
  build_files/base/16-bootc.sh
  build_files/base/17-cleanup.sh
  build_files/base/18-workarounds.sh
  build_files/base/19-initramfs.sh
  build_files/dx/01-install-copr-repos-dx.sh
  build_files/dx/02-install-kernel-akmods-dx.sh
  build_files/dx/03-packages-dx.sh
  build_files/dx/04-override-install-dx.sh
  build_files/dx/09-cleanup-dx.sh
  build_files/shared/build-base.sh
  build_files/shared/build-dx.sh
  build_files/shared/clean-stage.sh
Labels: enhancement, github_actions, lgtm, size:L

#144 chore: fix justfile
  Justfile
  just/aurora-apps.just
Labels: lgtm, size:XS

#145 feat(ci): add ujust recipe to list installed rpms
  .github/workflows/validate-just.yml
  just/aurora-apps.just
Labels: enhancement, github_actions, lgtm, size:M

#146 fix(artifacthub): remove artifacthub category
  Justfile
Labels: lgtm, size:XS

#151 fix(nvidia): use correct kernel flavor for akmods with stable-daily
  Justfile
Labels: bug, lgtm, size:XS

#153 fix: use libheif from Fedora to support older Intel platforms
  build_files/base/05-override-install.sh
Labels: lgtm, size:XS

#152 feat: Do not duplicate isos anymore and upload -hwe ones instead
  .github/workflows/reusable-build-iso.yml
Labels: github_actions, lgtm, size:S

#155 chore(build): port improvements from Bluefin's skew fixes
  build_files/base/01-build-fix.sh
Labels: lgtm, size:S

#159 feat: update stable kernel to 6.12.9
  .github/workflows/build-image-stable.yml
  Justfile
Labels: github_actions, lgtm, size:S

#162 fix: rename tmpfiles.d conf file
  system_files/shared/usr/lib/tmpfiles.d/usr-share-sddm-themes.conf
Labels: lgtm, size:XS

#166 feat: add udev rules on just recipe opentabletdriver
  just/aurora-apps.just
Labels: enhancement, lgtm, size:M
