Repository ublue-os/aurora, pull requests merged in 2025-10, with the labels that each got.

#1032 feat: default to new wallpaper
  build_files/base/07-base-image-changes.sh
Labels: enhancement, lgtm, size:XS

#1042 fix: aurora-docs errors
  system_files/shared/usr/share/applications/dev.getaurora.aurora-docs.desktop
Labels: documentation, lgtm, size:XS

#1041 fix: offline docs away from panel
  build_files/base/07-base-image-changes.sh
  build_files/base/11-bazaar.sh
Labels: enhancement, lgtm, size:XS

#1051 chore: add new mangohud runtime
  just/aurora-apps.just
Labels: lgtm, size:XS

#1059 feat(ci): ignore bazaar changes
  .github/workflows/build-image-beta.yml
  .github/workflows/build-image-latest-main.yml
  .github/workflows/build-image-stable.yml
Labels: github_actions, lgtm, size:XS

#1060 feat(bazaar): add more apps
  system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Labels: enhancement, lgtm, size:XS

#1062 fix: Improve argument parsing in kde-ptyxis script
  system_files/shared/usr/bin/kde-ptyxis
Labels: bug, lgtm, size:XS
