Repository ublue-os/aurora, pull requests merged in 2025-09, with the labels that each got.

#906 chore: remove already installed packages from packages.json
  packages.json
Labels: dependencies, lgtm, size:S

#920 fix(os-release): remove extra image info from os-release
  build_files/base/00-image-info.sh
Labels: lgtm, size:XS

#919 chore: unpin coreos-stable kernel
  .github/workflows/build-image-stable.yml
Labels: github_actions, lgtm, size:XS

#941 fix(bazaar): always use white text color
  system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Labels: bug, lgtm, size:XS

#966 chore: add missing images to cleanup workflow
  .github/workflows/clean.yml
Labels: github_actions, lgtm, size:XS

#975 fix: changelogs better formatting for authors
  .github/changelogs.py
Labels: lgtm, size:XS

#986 feat(bazaar): add ssh studio
  system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Labels: enhancement, lgtm, size:XS

#1017 chore: move ISO build to once a month
  .github/workflows/reusable-build-iso-anaconda.yml
Labels: github_actions, size:XS

#1026 feat: add yafi to bazaar
  system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Labels: enhancement, lgtm, size:XS

#1028 chore: move config back
  packages.json
  system_files/shared/etc/geoclue/conf.d/99-beacondb.conf
  system_files/shared/usr/share/plasma/avatars/echo.png
  system_files/shared/usr/share/plasma/avatars/lumina.png
  system_files/shared/usr/share/plasma/avatars/phlip.png
  system_files/shared/usr/share/plasma/avatars/scope.png
  system_files/shared/usr/share/plasma/avatars/tina.png
  system_files/shared/usr/share/plasma/avatars/vincent.png
  system_files/shared/usr/share/ublue-os/fastfetch.jsonc
  system_files/shared/usr/share/ublue-os/homebrew/aurora-ai.Brewfile
  system_files/shared/usr/share/ublue-os/homebrew/aurora-cli.Brewfile
  system_files/shared/usr/share/ublue-os/homebrew/aurora-fonts.Brewfile
  system_files/shared/usr/share/ublue-os/homebrew/kubernetes.Brewfile
Labels: lgtm, size:L

#1029 chore: remove bcache-tools
  packages.json
Labels: lgtm, size:XS
