Repository ublue-os/aurora, pull requests merged in 2025-06, with the labels that each got.

#545 chore: disable old rpm-ostreed-automatic.timer
  build_files/base/17-cleanup.sh
Labels: lgtm, size:XS

#461 feat: add ublue-branding-logos
  packages.json
Labels: enhancement, lgtm, size:XS

#555 feat: add new deployment notification to starship prompt
  system_files/shared/etc/skel/.config/starship.toml
Labels: enhancement, lgtm, size:XS

#561 fix: remove Framework 13 (AMD) udev workarounds with latest BIOS
  system_files/shared/usr/share/ublue-os/system-setup.hooks.d/10-framework.sh
Labels: framework, lgtm, size:M

#564 chore: add renner to codeowners
  .github/CODEOWNERS
Labels: size:XS

#566 fix: v4l2loopback
  build_files/base/03-install-kernel-akmods.sh
Labels: lgtm, size:XS

#570 feat: change Pika Backup to Vorta
  iso_files/system-flatpaks.list
Labels: enhancement, lgtm, size:XS

#547 chore: move to aurora-kde-config package
  build_files/base/05-override-install.sh
  system_files/shared/usr/share/backgrounds/aurora/aurora.xml
  system_files/shared/usr/share/plasma/look-and-feel/dev.getaurora.aurora.desktop/contents/defaults
  system_files/shared/usr/share/plasma/look-and-feel/dev.getaurora.aurora.desktop/contents/icons/aurora-logo.svg
  system_files/shared/usr/share/plasma/look-and-feel/dev.getaurora.aurora.desktop/contents/plasmoidsetupscripts/org.kde.plasma.folder.js
  system_files/shared/usr/share/plasma/look-and-feel/dev.getaurora.aurora.desktop/contents/plasmoidsetupscripts/org.kde.plasma.kickoff.js
  system_files/shared/usr/share/plasma/look-and-feel/dev.getaurora.aurora.desktop/contents/plasmoidsetupscripts/org.kde.plasma.systemtray.js
  system_files/shared/usr/share/plasma/look-and-feel/dev.getaurora.aurora.desktop/contents/previews/preview.png
  system_files/shared/usr/share/plasma/look-and-feel/dev.getaurora.aurora.desktop/contents/splash/Splash.qml
  system_files/shared/usr/share/plasma/look-and-feel/dev.getaurora.aurora.desktop/contents/splash/images/aurora_logo.svgz
  system_files/shared/usr/share/plasma/look-and-feel/dev.getaurora.aurora.desktop/contents/splash/images/busywidget.svgz
  system_files/shared/usr/share/plasma/look-and-feel/dev.getaurora.aurora.desktop/metadata.desktop
  system_files/shared/usr/share/plasma/look-and-feel/dev.getaurora.aurora.desktop/metadata.json
Labels: lgtm, size:L

#552 feat: change Boxbuddy to Distroshelf
  iso_files/system-flatpaks.list
Labels: enhancement, lgtm, size:XS

#583 fix: actually replace boxbuddy with distroshelf
  aurora_flatpaks/flatpaks
Labels: lgtm, size:XS

#589 Revert "chore(packages): remove fcitx packages"
  packages.json
Labels: lgtm, size:XS

#581 fix: jetbrains toolbox installation
  just/aurora-apps.just
Labels: lgtm, size:XS

#598 chore: remove libheif workaround
  build_files/base/05-override-install.sh
Labels: upstream, lgtm, size:S

#602 feat: use new wallpaper for README
  README.md
Labels: documentation, lgtm, size:XS

#560 fix: rework user setup hooks to use ublue-setup-services
  system_files/shared/usr/libexec/ublue-user-setup
  system_files/shared/usr/share/ublue-os/user-setup.hooks.d/40-flatpak.sh
  system_files/shared/usr/share/ublue-os/user-setup.hooks.d/50-ptyxis.sh
Labels: lgtm, size:L

#612 fix: use the kinoite-main to kickoff build
  .github/renovate.json5
  image-versions.yml
Labels: lgtm, size:XS

#616 chore: remove hidden desktop entry section for gnome-system-monitor
  build_files/base/07-base-image-changes.sh
Labels: lgtm, size:XS

#619 fix: rename the libvirt workaround service
  build_files/dx/09-cleanup-dx.sh
Labels: lgtm, size:XS

#620 chore: remove discover KNewStuff backend properly
  build_files/base/07-base-image-changes.sh
  packages.json
Labels: lgtm, size:XS

#621 fix: prevent plasma-firewall package skew
  build_files/base/05-override-install.sh
  packages.json
Labels: lgtm, size:S

#623 fix(flatpaks): remove fedora repos and avoid collision with fedora flatpaks
  just/aurora-system.just
Labels: lgtm, size:S

#631 docs: add deepwiki badge
  README.md
Labels: documentation, lgtm, size:XS

#638 fix: use white logo for rebasers
  build_files/base/07-base-image-changes.sh
Labels: lgtm, size:XS

#644 feat: add iwd
  packages.json
Labels: enhancement, lgtm, size:XS

#648 feat: add active user count badge to README
  README.md
Labels: documentation, lgtm, size:XS

#633 fix: add retry on curl in build scripts
  build_files/base/03-install-kernel-akmods.sh
  build_files/dx/04-override-install-dx.sh
Labels: bug, lgtm, size:XS

#655 fix(pin): qt6-qtwayland kscreenlocker regression
  build_files/base/18-workarounds.sh
Labels: bug, lgtm, size:XS

#615 feat: update aurora wallpaper for july
  build_files/base/07-base-image-changes.sh
Labels: lgtm, size:XS
