Repository ublue-os/aurora, pull requests merged in 2025-02, with the labels that each got.

#170 feat: install new flatpaks for current users on boot
  just/aurora-system.just
  system_files/shared/usr/libexec/ublue-flatpak-manager
Labels: enhancement, lgtm, size:M

#172 fix: flatpak comparison in ujust script
  build_files/base/18-workarounds.sh
  just/aurora-system.just
Labels: lgtm, size:M

#171 feat: add KCM for managing updates/rebasing
  packages.json
Labels: enhancement, lgtm, size:XS

#142 chore: unpin kernel on stable
  .github/workflows/build-image-stable.yml
  Justfile
Labels: github_actions, lgtm, size:XS

#176 fix: update funding
  .github/FUNDING.yml
Labels: size:XS

#150 feat: remove adw-gtk3 and inputleap from base image
  aurora_flatpaks/flatpaks
  packages.json
Labels: enhancement, lgtm, size:XS

#178 feat: update fastfetch logo to new logo
  system_files/kinoite/usr/share/ublue-os/aurora-logo.txt
  system_files/shared/usr/share/ublue-os/fastfetch.jsonc
Labels: enhancement, lgtm, size:M

#180 Revert "feat: update fastfetch logo to new logo"
  system_files/kinoite/usr/share/ublue-os/aurora-logo.txt
  system_files/shared/usr/share/ublue-os/fastfetch.jsonc
Labels: lgtm, size:M

#181 fix: make ujust update use direct calls to rpm-ostree and others
  system_files/shared/usr/share/ublue-os/just/10-update.just
Labels: bug, lgtm, size:XS

#179 fix: fail build if kf6-kio version skew detected
  Justfile
  build_files/base/05-override-install.sh
Labels: lgtm, size:S

#174 chore: un-cliwrap and use dnf5 instead of rpm-ostree
  Containerfile
  build_files/base/01-build-fix.sh
  build_files/base/02-install-copr-repos.sh
  build_files/base/03-install-kernel-akmods.sh
  build_files/base/04-packages.sh
  build_files/base/05-override-install.sh
  build_files/base/07-base-image-changes.sh
  build_files/base/09-hwe-additions.sh
  build_files/base/17-cleanup.sh
  build_files/base/19-initramfs.sh
  build_files/dx/01-install-copr-repos-dx.sh
  build_files/dx/02-install-kernel-akmods-dx.sh
  build_files/dx/03-packages-dx.sh
  build_files/dx/09-cleanup-dx.sh
  build_files/shared/build-base.sh
  build_files/shared/clean-stage.sh
Labels: lgtm, size:L

#183 fix: update topgrade.toml
  build_files/base/05-override-install.sh
  packages.json
  system_files/shared/usr/share/ublue-os/topgrade.toml
Labels: lgtm, size:S

#185 fix: remove bootc key from topgrade
  system_files/shared/usr/share/ublue-os/topgrade.toml
Labels: bug, lgtm, size:XS

#182 chore(ci): support combined akmods-kernel-cache in build
  Justfile
  build_files/base/03-install-kernel-akmods.sh
  build_files/dx/02-install-kernel-akmods-dx.sh
Labels: lgtm, size:M

#187 fix: make cursor smaller in gtk flatpaks when fractional scaling is enabled
  system_files/shared/usr/libexec/ublue-user-setup
Labels: lgtm, size:XS

#188 feat: change to CachyOS addons repo for scx-scheds package
  build_files/base/02-install-copr-repos.sh
  build_files/base/05-override-install.sh
  build_files/base/17-cleanup.sh
Labels: enhancement, lgtm, size:XS

#189 fix: Justfile to avoid collision with fedora flatpaks
  just/aurora-system.just
Labels: lgtm, size:XS

#190 feat: enable fw-fanctrl support (+ectool)
  build_files/base/02-install-copr-repos.sh
  build_files/base/17-cleanup.sh
  packages.json
Labels: enhancement, lgtm, size:XS

#194 feat(just): add aurora-specific changelogs
  system_files/shared/usr/share/ublue-os/just/10-update.just
Labels: enhancement, lgtm, size:XS

#195 feat: add font downloader and embelish for managing fonts
  aurora_flatpaks/flatpaks
  dx_flatpaks/flatpaks
  packages.json
Labels: enhancement, lgtm, size:S

#198 feat: add vfio modules to image
  just/aurora-system.just
  system_files/dx/usr/lib/dracut/dracut.conf.d/80-vfio.conf
  system_files/dx/usr/libexec/aurora-dx-kvmfr-setup
Labels: enhancement, lgtm, size:M

#199 chore: disable vscode automated updates
  system_files/dx/etc/skel/.config/Code/User/settings.json
Labels: size:XS

#204 fix: add 23.08 runtimes for mangohud and gamescope for lutris/heroic
  just/aurora-apps.just
Labels: lgtm, size:XS

#205 feat(dx): add ramalama
  packages.json
Labels: dependencies, lgtm, size:XS

#206 fix: only run ublue user services for human users
  system_files/dx/usr/lib/systemd/user/aurora-dx-user-vscode.service
  system_files/shared/usr/lib/systemd/user/ublue-flatpak-manager.service
  system_files/shared/usr/lib/systemd/user/ublue-user-setup.service
Labels: bug, lgtm, size:XS

#211 fix: correctly pass argument to `ujust install-system-flatpaks`
  system_files/shared/usr/libexec/ublue-flatpak-manager
Labels: lgtm, size:XS

#212 fix: put bash-prexec back
  build_files/base/05-override-install.sh
Labels: lgtm, size:XS

#214 feat: bring back kde-welcome
  packages.json
Labels: enhancement, lgtm, size:XS

#216 feat: add warning when user use dnf/yum
  system_files/kinoite/usr/bin/dnf
  system_files/kinoite/usr/bin/yum
Labels: enhancement, lgtm, size:XS

#219 feat: add nerd fonts fallback to vscode config
  system_files/dx/etc/skel/.config/Code/User/settings.json
Labels: enhancement, lgtm, size:XS

#220 feat: add beacondb geolocation for timezones
  system_files/shared/etc/geoclue/conf.d/99-beacondb.conf
Labels: enhancement, lgtm, size:XS

#225 fix: remove flatpak override for QT_QPA_PLATFORM
  system_files/shared/usr/libexec/ublue-user-setup
Labels: bug, lgtm, size:XS

#213 feat: add starship config
  system_files/kinoite/etc/skel/.config/starship.toml
Labels: enhancement, lgtm, size:L

#227 chore: small cleanup
  build_files/base/02-install-copr-repos.sh
  build_files/base/05-override-install.sh
  packages.json
  system_files/kinoite/usr/bin/yum
Labels: lgtm, size:S

#228 chore: remove alternatives workaround
  build_files/base/18-workarounds.sh
  build_files/shared/build-base.sh
  build_files/shared/build-dx.sh
Labels: lgtm, size:S

#221 feat: enable Terra repo and swap kf6-kio to use terra version
  build_files/base/02-install-copr-repos.sh
  build_files/base/05-override-install.sh
Labels: enhancement, lgtm, size:S

#230 fix: remove un-needed comments from gaming flatpak install recipe
  just/aurora-apps.just
Labels: size:XS

#233 feat: add KSystemLog
  packages.json
Labels: enhancement, lgtm, size:XS

#234 chore: use `ublue-os/packages` for ublue-related packages
  build_files/base/02-install-copr-repos.sh
  build_files/base/17-cleanup.sh
  build_files/dx/01-install-copr-repos-dx.sh
  build_files/dx/09-cleanup-dx.sh
Labels: lgtm, size:XS

#235 feat: add desktop entry for boot into windows easily
  .github/changelogs.py
  just/aurora-system.just
  system_files/kinoite/usr/bin/boot-to-windows
  system_files/kinoite/usr/share/applications/boot-to-windows.desktop
Labels: enhancement, lgtm, size:S

#236 fix: update package list to only include symbol nerd fonts
  packages.json
Labels: lgtm, size:XS

#243 feat: enable terra repo for dx building too
  build_files/base/17-cleanup.sh
  build_files/dx/01-install-copr-repos-dx.sh
  build_files/dx/09-cleanup-dx.sh
Labels: enhancement, size:S

#245 chore: pin latest to kernel 6.12
  .github/workflows/build-image-latest-hwe.yml
  .github/workflows/build-image-latest-main.yml
  .github/workflows/build-images.yml
Labels: github_actions, lgtm, size:M

#247 feat: add more fcitx5 plugin
  packages.json
Labels: enhancement, lgtm, size:XS
